name: Django Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory
        run: ls -d */

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test app_pr
